<a href="https://colab.research.google.com/github/optichkina/HomeworksGB/blob/main/lesson3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
def is_eig(A):
    w, v = np.linalg.eig(A)
    print(f'Матрица A:\n{A}')
    print(f'Собственные значения:\n{w}')
    print(f'Собственные векторы:\n{v}')

1. Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

In [2]:
A = np.array([[-1, -6], [2, 6]])
is_eig(A)

Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


2. Пусть линейный оператор задан матрицей.установить, является ли вектор х=(1,1) собственным вектором этого линейного оператора.



In [3]:
A = np.array([[1, 1], [-1, 3]])
is_eig(A)

Матрица A:
[[ 1  1]
 [-1  3]]
Собственные значения:
[2.00000002 1.99999998]
Собственные векторы:
[[ 0.70710677 -0.70710679]
 [ 0.70710679 -0.70710677]]


4. Пусть линейный оператор задан матрицей.Установить, является ли вектор x=(3, -3, -4) собственным вектором этого линейного оператора.

In [4]:
A = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
is_eig(A)

Матрица A:
[[0 3 0]
 [3 0 0]
 [0 0 3]]
Собственные значения:
[ 3. -3.  3.]
Собственные векторы:
[[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
